### ISSUE TITLE
Error on Activation

### ISSUE THREAD

**Issue by oakdalesoft** [aramk/crayon-syntax-highlighter#132]
Fatal error: Allowed memory size of 33554432 bytes exhausted (tried to allocate 491520 bytes) in .../wp-content/plugins/crayon-syntax-highlighter/crayon_formatter.class.php on line 481

**Comment by CKMacLeod** [comment]
Possibly same error upon attempted activation in multi-site installation - "Plugin could not be activated because it triggered a fatal error." Have just begun research, and have just opened new issue. Could you be more specific about "simple swap file" changes?
