### ISSUE TITLE
Not working when post published with XMLRPC

### ISSUE THREAD

**Issue by matrixik** [aramk/crayon-syntax-highlighter#14]
Hello,

highlighting not working when I add post to blog with XMLRPC protocol.
Example:
http://testowe.binhoster.com/2012/08/test-xmlrpc-posting-2/

If I go to post and push 'Update' button by hand then highlighting start working again:
http://testowe.binhoster.com/2012/08/test-xmlrpc-posting/

Best regards

P.S. I added post with Python code:

``` python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from wordpress_xmlrpc import Client, WordPressPost
from wordpress_xmlrpc.methods import posts

client = Client('http://exampleblog.com/xmlrpc.php', 'login', 'password')

post = WordPressPost()
post.title = 'Test xmlrpc posting'
post.content = """
<pre title="Test title">
some code
</pre>

[html title="Some HTML code"]
<a href="http://www.example.com">Test link</a>
[/html]
"""
post.post_status = 'publish'
post.id = client.call(posts.NewPost(post))
```

**Comment by michaelmcdonald** [comment]
Any updates on this issue? Any third party application that posts to my blog is not having code published correctly handled by Crayon.

**Comment by aramk** [comment]
No updates as of yet, I haven't had time to look into it. Would be happy if someone could tinker and make a PR though.
