### ISSUE TITLE
Adding csh to git project results in fatal error

### ISSUE THREAD

**Issue by SimonHarte** [aramk/crayon-syntax-highlighter#148]
I just tried to install crayon syntax highlighter and now I get an error pop-up in sourcetree saying: `'git status' failed with code 128:'fatal: Not a git repository: public/wp-content/plugins/crayon-syntax-highlighter/js/jquery-colorpicker/../../.git/modules/js/jquery-colorpicker'`

**Comment by pssplmaulikshah** [comment]
fatal: Not a git repository: wp-content/plugins/crayon-syntax-highlighter/langs/
vbnet/../../.git/modules/langs/vbnet

**Comment by aramk** [comment]
Fixed that - the submodule was renamed.
