### ISSUE TITLE
Multisite - wiil activate, but not show editor anywhere

### ISSUE THREAD

**Issue by shaneholloman** [aramk/crayon-syntax-highlighter#152]
Im on WP 3.8.1
Multisite
I tried network activate and single activate but not dice for me.... is this a known issue on multisite?

**Comment by firecopstation6** [comment]
Works fine on WP 4.1 Multisite. Just installed and did the network activate. It shows up and works in the new post just fine.
![crayon-on-wp-multisite-menu](https://cloud.githubusercontent.com/assets/685479/5693543/3b3238a0-98ef-11e4-8425-b789a26ec3d0.png)
