### ISSUE TITLE
WordWrap long sequence of characters without spaces

### ISSUE THREAD

**Issue by egru** [aramk/crayon-syntax-highlighter#226]
I'm having an issue where I have a long string and when I try to wordwrap, it only does it if there is a space anywhere in the string. Otherwise it's going to have a horizontal scroll bar for the length of the whole thing. Is there some way to fix this?

**Comment by egru** [comment]
I fixed this by adding word-break: break-all to the wrapped css.

**Comment by aramk** [comment]
Cheers that fixed it. I've pushed the latest changes as 2.6.10.
