### ISSUE TITLE
Internal server error on Wordpress 4.1 with plugin 2.6.9

### ISSUE THREAD

**Issue by stephankn** [aramk/crayon-syntax-highlighter#238]
Updated plugin to 2.6.9 from 2.6.8 on wordpress 4.1.
Getting internal server error 500 when accessing dashboard and unable to create new posts.

disabling the pugin makes it work again.

Unfortunately access to server logs on my hosting is limited so no further error messages available.

error here:

```
/wp-admin/admin-ajax.php?action=dashboard-widgets&widget=dashboard_primary&pagenow=dashboard
```

and here:

```
/wp-admin/post-new.php
```

Trying to re-enable the plugin fails with a memory allocation problem.

```
Fatal error: Allowed memory size of 67108864 bytes exhausted (tried to allocate 71 bytes) in /var/www/web247/html/wp-includes/pomo/streams.php on line 100
```

Leaving this comment in case other users had the same issue and can contribute more information.

**Comment by originalwebgurl** [comment]
Our team has been seeing the same error on v2.6.8 for about 4 weeks now on WP 4.2.2. , we're updating to 2.7.1 to see if it will resolve the error. If it doesn't I'll try to provide some more debug details.

**Comment by n3iTh4N** [comment]
Also experiencing the same problem. Just letting you know. Been a fan of your work. Hoping this gets fixed the soonest.

**Comment by stephankn** [comment]
Looks fixed, so closing the issue to not pile up unresolved issues. Chances are high that as mentioned above issue is not caused directly by crayon.
