### ISSUE TITLE
About the plugin with the new theme Twenty Fifteen

### ISSUE THREAD

**Issue by hcl** [aramk/crayon-syntax-highlighter#242]
Hi, I'm a user of your beautiful plugin. But now I have a little problem when use it. I just update my WordPress version and use its new theme Twenty Fifteen. But when I move my mouse over the side of the code box, the code in it will flash between the high-light mode and pure-text mode very quickly. I'm confused with the problem and hope to get the solution. 
Sorry for my poor English.

**Comment by noideaboy** [comment]
This piece of code fixed the issue for me:
table.crayon-table {
  table-layout: auto;
}
The theme has table's table-layout set to fixed, so changing that fixes the issue. You can see the plugin working fine with 2015 here: http://wordpressaholic.com/ Awesome plugin Aramk!

**Comment by aramk** [comment]
Thanks @noideaboy, that fix worked great! Updated in 0bff0c3.
