### ISSUE TITLE
Potential security issue

### ISSUE THREAD

**Issue by ksubileau** [aramk/crayon-syntax-highlighter#247]
Hello,
While I'm trying your plugin for a potential future usage, I think I found an important security breach, that can reveal some critical data. How can I send you more details ?

**Comment by aramk** [comment]
Hi there, you could email me at crayon.syntax at gmail?

**Comment by ksubileau** [comment]
I sent you the details by email Sunday.

**Comment by ksubileau** [comment]
Version 2.7.0 fixes the issue.
I released a [blog post explaining the details of this vulnerability](http://www.kevinsubileau.fr/informatique/hacking-securite/crayon-syntax-highlighter-local-file-disclosure-vulnerability.html) in order to inform users and urge them to update quickly.

**Comment by aramk** [comment]
Hi Kevin,Thanks for that!




Cheers,

Aram
