### ISSUE TITLE
Theme change when multiple <pre> blocks

### ISSUE THREAD

**Issue by razy69** [aramk/crayon-syntax-highlighter#252]
Hi,
I don't know if it's a miss config from myself, or if it's a bug.
When i insert multiple < pre > blocks, the theme is changing one out of two.

here is the link : http://admintips.fr/script-firewall-avec-iptables/

**Comment by maesa** [comment]
Yeah, can confirm this, it happens with my blog too

**Comment by aramk** [comment]
Hi @razy69, is this still occurring? I can't see it on that link I don't think.

**Comment by maesa** [comment]
https://halfnor.ml/2015/03/disable-and-remove-wordpress-revisions/

*Second code block

**Comment by aramk** [comment]
It appears a script is causing it on your site. It's adding an "alt" class to the following element:

```
<tr class="crayon-row alt">
<td class="crayon-nums " data-settings="show">
<div class="crayon-nums-content" style="font-size: 12px !important; line-height: 15px !important;"><div class="crayon-num" data-line="crayon-5520b3be1c36f024690906-1">1</div></div>
</td>
<td class="crayon-code"><div class="crayon-pre" style="font-size: 12px !important; line-height: 15px !important; -moz-tab-size:4; -o-tab-size:4; -webkit-tab-size:4; tab-size:4;"><div class="crayon-line" id="crayon-5520b3be1c36f024690906-1"><span class="crayon-e">define</span><span class="crayon-sy">(</span><span class="crayon-s">'WP_POST_REVISIONS'</span><span class="crayon-sy">,</span><span class="crayon-h"> </span><span class="crayon-cn">3</span><span class="crayon-sy">)</span><span class="crayon-sy">;</span></div></div></td>
</tr>
```

There's also this style which then causes the color change:

```
.entry table tr.alt {
  background: #e9e9e9;
}
```

**Comment by maesa** [comment]
I've found the culprit. Currently, I'm using [Anew](https://github.com/AlxMedia/anew) theme.

On line 69 (wp-content/themes/anew/js/script.js).

Change
```javascript
$('table tr:odd').addClass('alt');
```
to
```javascript
$('table:not(.crayon-table) tr:odd').addClass('alt');
```

**Comment by aramk** [comment]
Good to hear!

**Comment by razy69** [comment]
Hi ! sorry i will try it thanks maesa, and sorry for this issue aramk :D

**Comment by razy69** [comment]
i confirm it works very well !!! Thanks
