### ISSUE TITLE
Capture <pre> tags as Crayons breaks css

### ISSUE THREAD

**Issue by CatalinPrata** [aramk/crayon-syntax-highlighter#253]
Hello, first of all thanks for the plugin!

I want to use Crayon now, previously I used another plugin to style the code.. now the problem is that if I enable the plugin with the defaults and let the "Capture < pre > tags as Crayons" checked, the site is not able to render any css and the page gets like a blank notepad document. If I uncheck that, I can see the page rendered as it should but the thing is that the css for Crayon is not added to the header/page and the code is not highlighted.. 
Anyone knows how to fix this? Is this a known issue?

Platform:
Wordpress: 4.1
All the previous code highligter plugins uninstalled.

Thanks

**Comment by aramk** [comment]
Hi @CatalinPrata,
I think you'll need to look into the page source for why this might be occurring - is it generating partially correct output. It could be a missing `</pre>` which is preventing it from rendering, or perhaps it's related to CSS. Does it occur if you have no Crayon tags on the page? Do you get an PHP errors in the log file?

**Comment by CatalinPrata** [comment]
@aramk thanks for your reply. 
I checked one of my pages and I couldn't find any issues there, on the page I have the following:
The css is loaded like this: 

    <link
    rel='stylesheet' href='http://www.myandroidsolutions.com/wp-content/plugins/wp-minify-fix/min/?f=wp-content/plugins/wordpress-easy-paypal-payment-or-donation-accept-plugin/wpapp-styles.css,wp-includes/css/dashicons.min.css,wp-includes/css/admin-bar.min.css,wp-content/plugins/crayon-syntax-highlighter/css/min/crayon.min.css,wp-content/plugins/cookie-law-info/css/cli-style.css,wp-content/plugins/wp-pro-quiz/css/wpProQuiz_front.min.css,wp-content/themes/twentytwelve/style.css,wp-content/plugins/wp-social-seo-booster/includes/css/wps-seo-booster-front.css&amp;m=1422382986' type='text/css' media='screen' />

And javascript:

    <script type='text/javascript' src='http://www.myandroidsolutions.com/wp-content/plugins/wp-minify-fix/min/?f=wp-content/themes/twentytwelve/js/html5.js,wp-includes/js/jquery/jquery.js,wp-includes/js/jquery/jquery-migrate.min.js,wp-content/plugins/crayon-syntax-highlighter/js/min/crayon.min.js,wp-content/plugins/cookie-law-info/js/cookielawinfo.js,wp-content/plugins/google-publisher/js/previewloader.js,wp-content/plugins/google-analyticator/external-tracking.min.js&amp;m=1422382986'></script>

I have a pre tag like this:

    <pre class="lang:xhtml decode:true" title="Android custom attributes">&lt;?xml version="1.0" encoding="utf-8"?&gt;
    &lt;resources&gt;
        &lt;!-- Define our custom attributes to be used on the TextView or where we need --&gt;
        &lt;declare-styleable name="LocalizationAttributes"&gt;
            &lt;attr name="locText" format="string" /&gt;
        &lt;/declare-styleable&gt;
    &lt;/resources&gt;</pre>

The page checked is this: http://www.myandroidsolutions.com/2015/01/15/load-localized-strings-at-runtime/


Also the log for Crayon is:

    [Crayon Syntax Highlighter Log Entry - 6:27:45 PM - 27 Jan 2015]
    
     [CrayonUtil::lines()] 'Cannot read lines at \'/langs/go/statement.txt\'.'
     [SYSTEM LOG] 'Parsing of \'/langs/go/go.txt\' failed, an (?alt) tag failed for the element \'STATEMENT\''
    
    [Crayon Syntax Highlighter Log Entry - 6:42:26 PM - 27 Jan 2015]
    
     [SYSTEM LOG] 'Upload directory is empty:  cannot load languages.'
     [SYSTEM LOG] 'The resource directory is missing, should be at \'\'.'
     [CrayonUtil::lines()] 'Cannot read lines at \'default/default.txt\'.'
    
    [Crayon Syntax Highlighter Log Entry - 6:42:31 PM - 27 Jan 2015]
    
     [SYSTEM LOG] 'Upload directory is empty:  cannot load languages.'
     [SYSTEM LOG] 'The resource directory is missing, should be at \'\'.'
     [CrayonUtil::lines()] 'Cannot read lines at \'default/default.txt\'.'

I could fix the errors in the crayon logs by changing something in the go language file but that didn't fix the issue.
Thanks

**Comment by aramk** [comment]
You could try to disable all other plugins and enable them one at a time, in particular the `wp-minify-fix` plugin.

**Comment by yongpro** [comment]
I have same issue...

```
 [Crayon Syntax Highlighter Log Entry - 4:48:32 AM - 05 Mar 2015]

 [CrayonUtil::lines()] 'Cannot read lines at \'/langs/go/statement.txt\'.'
 [SYSTEM LOG] 'Parsing of \'/langs/go/go.txt\' failed, an (?alt) tag failed for the element \'STATEMENT\''`
```

**Comment by yongpro** [comment]
If use follow tag, Crayon will have effect:
```
[crayon lang="java", title="Code：IMobileStorage"]
[/crayon]
```
But if use above tag, when return from Text view to Visualization view in Wordpress Editor, bank will auto clear in my code, no format... so now only use pre to active Crayon, but no effect.

You can check phenomenon on my test article: 
[http://www.zhaocs.info/java-learning-interface-02.html](http://www.zhaocs.info/java-learning-interface-02.html)

**Comment by CatalinPrata** [comment]
@aramk so it seems that it finally works, I enabled again these options:
-  Capture <pre> tags as Crayons 
-  Load scripts in the page footer using wp_footer() to improve loading performance.

Sample: http://www.myandroidsolutions.com/2015/04/08/android-back-directly-to-root-activity/ 

Maybe I have some plugins that are interfering with the js or css, even though I tried to disable one by one with no results..

Thanks for the great plugin!

**Comment by aramk** [comment]
There's been a few cases where external js and css have affected Crayon. Glad you've got it working.
