### ISSUE TITLE
Title not appearing. Missing title in pre tag.

### ISSUE THREAD

**Issue by RehanSaeed** [aramk/crayon-syntax-highlighter#255]
Visit <a href="http://rehansaeed.co.uk/reactive-extensions-part7-sample-events/">this</a> page. You will notice that the title's on the crayon syntax highlighter code is not shown at all. It is not hidden, if you look at the page source, it is just not there.

I am using WordPress 4.1. Both of the code blocks have titles set in the WordPress post editor, as shown below:

<pre>&lt;pre title="WPF TextChanged Event Causing Problems" class="lang:c# decode:true "&gt;this.TextBox.TextChanged += this.OnTextBoxTextChanged;

private void OnTextBoxTextChanged(object sender, TextChangedEventArgs e)
{
    // Heavy User Interface updates that can cause the application to lock up.
}&lt;/pre&gt;</pre>

**Comment by RehanSaeed** [comment]
I've discovered that having the title as the first attribute in the pre tag is causing the issue. After moving it to the last attribute everything works. Ideally crayon should be able to handle this. This behaviour must have changed because my older posts have the title at the beginning and crayon used to work.

**Comment by aramk** [comment]
This is fixed in a44dd8cfc17629b64f0a3d74fd2364bfdad7dd72.
