### ISSUE TITLE
Uh, tab-size have some trouble

### ISSUE THREAD

**Issue by ChouUn** [aramk/crayon-syntax-highlighter#256]
* At the beginning, pardon me because of my __poor__ English.

* This is my code displayed in __eclipse__. And in __markdown__, it‘s also right.
```cpp
#define mp(a,b)		make_pair(a,b)
#define X			first
#define Y			second
```

* But in [My Blog](http://www.fateud.com/2015/codetemplate/) with Crayon, the code of __standard.h__ appear like this : 
```cpp
#define mp(a,b)        make_pair(a,b)
#define X          first
#define Y          second
```
* My setting is : __Tab-size__ = _4_; __convert tabs to spaces__ = _false_;
So I think the calculation of spaces have some matters,
and wanna inquiry why my tabs convert to spaces __automatically__.

* Finally, thx for ur time.

**Comment by aramk** [comment]
Hi, I believe that might be a bug

**Comment by ChouUn** [comment]
THX, Everything returns to normal.
