### ISSUE TITLE
HTML code within pre tags

### ISSUE THREAD

**Issue by egru** [aramk/crayon-syntax-highlighter#260]
Hello,

I want to use html code inside my pre tags to highlight some text like this:

`<pre class="lang:default decode:true">&lt;span style="color: #ff0000;"&gt;test&lt;/span&gt;</pre>`

However, my page displays this:

`<span style="color: #ff0000;">test</span>`

and not just test in red. Is there a way to do this in crayon?

Thanks

**Comment by aramk** [comment]
Check the html post editor for what will be displayed. Since you've encoded your span tag with `&lt;` it will render as text. You could change it to a tag, but that could produce unusual results since you're now inserting HTML markup in your code that you don't want to treat as code.

**Comment by egru** [comment]
I tried that but it doesn't seem to work. Here's what the visual editor looks like:

![image](https://cloud.githubusercontent.com/assets/381117/6783602/95f2cb38-d148-11e4-8cb7-f390c700d31e.png)

Here's the text editor:

![image](https://cloud.githubusercontent.com/assets/381117/6783619/acc92622-d148-11e4-9773-431cb2b3586c.png)

The page then looks like this:

![image](https://cloud.githubusercontent.com/assets/381117/6783632/c27064cc-d148-11e4-86bd-aa850f0327fe.png)
