### ISSUE TITLE
Only load script asynchronously

### ISSUE THREAD

**Issue by isaumya** [aramk/crayon-syntax-highlighter#261]
Hi, it would be great is you can load the scripts `asynchronously`.

**Comment by aramk** [comment]
You can tell Crayon to only load the scripts if it's used on that page, but this may not work on all templates.

**Comment by isaumya** [comment]
I've edited the question. Please re-read my question it's not about loading scripts on specific page any more.

**Comment by aramk** [comment]
Do you mean loading the actual Crayon code asynchronously? Or loading the resource scripts (Crayon JS scripts and CSS styles) asynchronously? If it's the latter that should be handled by the browser.

**Comment by isaumya** [comment]
Yes I'm talking about loading resource scripts (Crayon JS scripts) asynchronously. Also this can't be handled by the browser unless you add `async` or `async=true` in your script loading url.

See this: http://www.w3schools.com/tags/att_script_async.asp
