### ISSUE TITLE
Incompatibility With The SB Child List plugin.

### ISSUE THREAD

**Issue by gbmhunter** [aramk/crayon-syntax-highlighter#269]
I have confirmed (with something like a 99% confidence interval) a incompatibility with SB Child List and the Crayon Syntax Highlighter plugin.

When both the shortcode `[sb_child_list]` and Crayon Syntax highlighted code is on the same page (and the page has a child page, so that the child list is displayed), the code fails to display correctly, but rather just shows something like `[crayon-55470dca1ff2a338621850/]`.

I have tested this with a fresh install of WordPress, with only the SB Child list and Crayon Syntax Highlighter plugins installed.

You can check out http://preview.erpsomq796s6pqfrhxi55lwl13g9o1oryc49y6784amgf1or.box.codeanywhere.com/test-page/ to see the results.

This is also affecting my site, http://www.mbedded.ninja.

**Comment by gbmhunter** [comment]
I have done more digging into this issue, and detailed the information here:
http://www.mbedded.ninja/site-admin/conflict-with-child-page-list-and-code-highlighter-style-plugins

**Comment by aramk** [comment]
Thanks for looking into that @gbmhunter, let me know if you suspect code changes are necessary in Crayon as well as SB Child List.

**Comment by gbmhunter** [comment]
Hi @aramk, no changes needed at this point, I think it's an issue with SB Child List and not Crayon.
