### ISSUE TITLE
".git" files from submodules in wordpress plugin

### ISSUE THREAD

**Issue by patwork** [aramk/crayon-syntax-highlighter#270]
Hi,

There's a small problem with submodules in crayon-syntax-highlighter. Two ".git" files are included in zip file which is downloaded from wordpress site.

```
./js/jquery-colorpicker/.git
./langs/vbnet/.git
```

Because of them, git cannot update repository (I have a repo with backup of all files in my wordpress blog).

```
git add -A
fatal: Not a git repository: js/jquery-colorpicker/../../.git/modules/js/jquery-colorpicker
```

**Comment by JoshShashaty** [comment]
I also have this issue.  I'll remove these manually and hope for these not to exist in next update.

**Comment by aramk** [comment]
I ran these two commands:
```
svn propset svn:ignore js/jquery-colorpicker/.git .
svn propset svn:ignore langs/vbnet/.git .
```
I can't see changes in `svn st`, but I suspect it's because they are hidden files? I'll push that in the next version.
