### ISSUE TITLE
Can codes from "url"  be updated ?

### ISSUE THREAD

**Issue by ChouUn** [aramk/crayon-syntax-highlighter#271]
Uh..
I use the __url__ attribute to load a file from _GitHub_,
but it seems not be __synchronized__ on blog when I updated.
How can I deal with it ? thx

**Comment by aramk** [comment]
See the setting "Clear the cache used to store remote code requests". By default it is daily to reduce requests. You can click "Clear Now" or set it to "Immediately".

**Comment by ChouUn** [comment]
sorry. thx

**Comment by aramk** [comment]
No worries, glad to have helped!
