### ISSUE TITLE
match groups in regexps?

### ISSUE THREAD

**Issue by hellt** [aramk/crayon-syntax-highlighter#283]
Hello, Aram
Is it me or regexp syntax for langs does not support match groups?
I tried to match a subset of a string with regexp `\*??[AB]:.*?[#$]\s(.+?\n)` and ended up with the whole string matched instead of a group specified in brackets   `(.+?\n)`

**Comment by aramk** [comment]
Hi @hellt, that's correct - the whole match will be included. I've used lookaheads and lookbehinds to allow specifying further conditions based on the surrounding content.
