### ISSUE TITLE
Showing Pre-formatted C-Code

### ISSUE THREAD

**Issue by suchja** [aramk/crayon-syntax-highlighter#284]
Hi,

thanks for this wonderful plugin!

Just started using it and wondered how best to integrate it. I do have articles with code snippets that are already pre-formatted. This basically comes from writing all my posts in markdown and converting them to HTML. So my C-code looks like the example below. Unfortunately Crayon shows all the html tags, which I obviously don't need and want.

I can change some things during conversion from md to html, but I'm not sure exactly what is the best approach to take to have a descent result in Crayon.

Many thanks and keep up the good work!
Jan
```html
<div class="sourceCode">
<pre class="sourceCode c"><code class="sourceCode c"><span class="dt">int</span> main(<span class="dt">void</span>)
{ 
  <span class="dt">float</span> eingelesenerRadius, volumen;

  printf(<span class="st">"Programm zur Berechnung des Volumens einer Kugel"</span>);
  printf(<span class="st">"</span><span class="ch">\n\n</span><span class="st">Radius der Kugel in cm: "</span>);
  scanf(<span class="st">"%f"</span>, &amp;eingelesenerRadius);

  volumen = BerechneKugelVolumen(eingelesenerRadius);
  printf(<span class="st">"Volumen: %f Kubikzentimeter</span><span class="ch">\n</span><span class="st">"</span>, volumen);

  <span class="kw">return</span> EXIT_SUCCESS;
}</code></pre>
</div>
```

**Comment by aramk** [comment]
Basically you'll want to have a `<pre></pre>` tag surrounding the plain text code. At the moment your output has HTML tags within the code itself which should be removed to prevent being formatted alongside your code.

**Comment by suchja** [comment]
Perfect! After some trying I figured out how the markdown to html converter (pandoc) creates a `<pre class="lang:c">` for me and leaves everything else untouched.

**Comment by aramk** [comment]
Nice, glad you got it working!
