### ISSUE TITLE
Not displaying correctly

### ISSUE THREAD

**Issue by giventoflyfish** [aramk/crayon-syntax-highlighter#286]
I'm running the latest version of Wordpress and Crayon Syntax Highlighter and I can't get it to display correctly. This is what it looks like. Any ideas on what I could be doing wrong?

![crayon](https://cloud.githubusercontent.com/assets/1375155/8640474/17537ef8-28c8-11e5-9ed5-c4e99a5e93e0.png)

**Comment by aramk** [comment]
This is caused by CSS I think. Verify that the Crayon CSS is available in the page source.

**Comment by giventoflyfish** [comment]
I didn't see anything for css related to crayon. I manually added crayon.min.css to my header and I do see generic layout now but not the theme that I selected.

I also noticed that there were some new directories in my upload folder and under Themes, Fonts and Lang there are no folders and files.

Any idea on what happened?

**Comment by giventoflyfish** [comment]
I deleted and reinstalled but still have the same issues.

**Comment by aramk** [comment]
The wordpress header in the template should be adding the styles automatically. If it isn't I think the theme may be the issue. There should be a Crayon theme (e.g. classic) as well.

**Comment by giventoflyfish** [comment]
That could be the problem. I get different, but not correct results if I run it locally. The template is 100% custom. Let me look into it further and see what is going on.

**Comment by giventoflyfish** [comment]
This was a theme issue. Once I fixed the theme, it works correctly. Thanks!
