### ISSUE TITLE
Code highlighting plug-in lead to ajax page load time is too long

### ISSUE THREAD

**Issue by mritd** [aramk/crayon-syntax-highlighter#291]
## On my website http://mritd.me due to use this code highlighting plug-in Lead to the home page load time is too long, the theme of my wordpress blog using ajax, highlighting the plugin I think may be due to the code In an attempt to render all articles in home page;Whether can add a code to specify URL highlighting rendering function?

在我的网站 http://mritd.me 上由于使用这个代码高亮插件 导致主页加载时间过长,我的 wordpress blog使用了 ajax 的主题,我认为可能是由于 这个代码高亮插件 在尝试 渲染主页的 所有文章导致的；是否可以增加一个对指定URL 进行代码高亮渲染的功能?

**Comment by aramk** [comment]
Hi, not sure what you waned from the rendering function.
