### ISSUE TITLE
Wiki Update - broken images

### ISSUE THREAD

**Issue by janicego** [aramk/crayon-syntax-highlighter#293]
The documentation wiki isn't loading the graphics.

**Comment by aramk** [comment]
Could you mention which URL has the missing graphics?

**Comment by janicego** [comment]
Hi @aramk Everything under https://github.com/aramk/crayon-syntax-highlighter/wiki

**Comment by aramk** [comment]
Unfortunately my site was hacked in 2011-2012 and I lost a lot of those images. The new site is with GitHub Pages so there's no chance of that.
