### ISSUE TITLE
Repo link

### ISSUE THREAD

**Issue by szepeviktor** [aramk/crayon-syntax-highlighter#301]
Could you modify the repo link to https://wordpress.org/plugins/crayon-syntax-highlighter/ ?
It is a 404 now.

**Comment by aramk** [comment]
Fixed in 4488088c3e992466c930d0603b148ff9efdacb08

**Comment by szepeviktor** [comment]
Thanks.

I've meant on the top of this page: https://github.com/aramk/crayon-syntax-highlighter

**Comment by aramk** [comment]
Ah yep fixed
