### ISSUE TITLE
Invalid Characters on browser

### ISSUE THREAD

**Issue by robsonalves** [aramk/crayon-syntax-highlighter#307]
Hey  guys looks this, the characteres doesn't show and I no have idea why it's happens.

![image](https://cloud.githubusercontent.com/assets/798072/10396643/01504db4-6e7a-11e5-992b-656ef6425f91.png)

When I Click in Raw mode it's works.

![image](https://cloud.githubusercontent.com/assets/798072/10396665/1f853920-6e7a-11e5-9804-74b280344fc9.png)

Thanks for great plugin!

**Comment by aramk** [comment]
Hi there,
It looks like you may have unicode whitespace that the parser attempts to format but ends up breaking perhaps. Could you paste this into a hex editor or maybe remove the space characters that are causing the issue and re-type them again?

**Comment by robsonalves** [comment]
Hi aramk.

I solved this changing the language to C#...
I made a mistake keeping a different language.

Ty!
