### ISSUE TITLE
Assets do not check for https

### ISSUE THREAD

**Issue by jessecooper** [aramk/crayon-syntax-highlighter#308]
I am currently trying to get my SSL rating up and have been getting the following errors with the plugin:

Insecure URL: http://site/wp-content/plugins/crayon-syntax-highlighter/css/min/crayon.min.css?ver=f8b808f64de8a74faeaa4d5dc7142c3f
Found in: https://site/ 
...

Is the plugin set to detect HTTPS and I have a singular issue or is this something that needs to be added to the plugin?

**Comment by aramk** [comment]
Hmm, I'm using `wp_enqueue_style()` not hard coding the URLs. I guess you could use [this](http://wpquestions.com/question/showChrono/id/9298) strategy to change the URLs to include "https".

**Comment by jessecooper** [comment]
Thanks for the response. You will be happy to know it was not an issue with the plugin. The errors was because of the initial setup of the site before having https enabled. So those entries went into the sql database with http://site/ and did not get updated when it was switched to https. We did a manual update to the older entries and now everything is fine. Thanks for all your work on this plugin, and I hope this helps anyone who might run into the same issue we had.

**Comment by aramk** [comment]
Ah ok, glad you got it resolved.
