### ISSUE TITLE
Crayan Syntax highlighter not showing my xml code properly

### ISSUE THREAD

**Issue by rubanraj54** [aramk/crayon-syntax-highlighter#317]
I have installed "Crayon Syntax Highlighter" plugin in my wordpress site.

It is not showing my XML code properly. This is my actual XML code

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
package="androidumps.activeandroid" >

<application
android:name=".InitApplication"
android:allowBackup="true"
android:icon="@mipmap/ic_launcher"
android:label="@string/app_name"
android:theme="@style/AppTheme" >

<meta-data
android:name="AA_DB_NAME"
android:value="rootdatabase.db" />

<meta-data
android:name="AA_DB_VERSION"
android:value="1" />
<activity
android:name=".MainActivity"
android:label="@string/app_name" >

When i see it in my website, It is looking like this,  I dont what is this "&lt" and "&gt"

![yni7s](https://cloud.githubusercontent.com/assets/10024405/11293680/1c4eff56-8f82-11e5-8461-1dde67dfaa68.png)

**Comment by aramk** [comment]
Ensure you type that into the Tag Editor (<> button) or it won't format correctly. The reason is that pasting `<` into the visual editor will treat that as `&lt;` in the html editor.
