### ISSUE TITLE
Source Code Pro

### ISSUE THREAD

**Issue by thenoizz** [aramk/crayon-syntax-highlighter#323]
Can you please add Source Code Pro to the font list? https://www.google.com/fonts/specimen/Source+Code+Pro

**Comment by aramk** [comment]
Sure - note that you can add user themes, langs, and fonts in `wp-content/uploads/crayon-syntax-highlighter` in the same format as you find them in the plugin directory.

**Comment by aramk** [comment]
I've added this in db84ae38fbb1602776ff384c416a46804cf119c6

**Comment by thenoizz** [comment]
Wow, cool, thx a lot ;-)

**Comment by aramk** [comment]
:+1:
