### ISSUE TITLE
Style I choose is never applied to code blocks

### ISSUE THREAD

**Issue by SoboLAN** [aramk/crayon-syntax-highlighter#326]
Hello.

I'm very new to Wordpress. I installed the blog (4.0.9), added a few posts and I installed this plugin.

Now, when I add code blocks in my posts, no matter what styling and settings I change, the code is always rendered in the same way. Style settings, font settings, lines settings.... nothing works.

I think the main blog theme is overriding the plugin's CSS, although it would be weird since its one of the default themes that the Wordpress installation comes with.

When inspecting the HTML on Post Preview I can see the properties for the `pre` tag are coming from the theme's CSS file. Maybe they shouldn't.

I just don't get it. Everything works great about this plugin, except for the actual rendering of the code (which is whole point).

What am I missing ? I'll search for other plugins in the mean time...

**Comment by aramk** [comment]
I'm guessing it's as you say - the CSS. If you can post the content of the
post from the HTML editor, and tell me the theme you're using, that would
be reasonably easy to debug.
