### ISSUE TITLE
Font Request: Hack

### ISSUE THREAD

**Issue by TheFiZi** [aramk/crayon-syntax-highlighter#327]
Could this font be added as a choice to Crayon?

https://github.com/chrissimpkins/Hack

I had it manually hacked in before but it was causing upgrade issues so I'm back to stock.

**Comment by aramk** [comment]
You can add fonts in wp-content/uploads/crayon-syntax-highlighter in the same format as you find them in the plugin directory and they will remain after plugin updates.
