### ISSUE TITLE
Crash with WordPress 4.5 and bbPress

### ISSUE THREAD

**Issue by sesom42** [aramk/crayon-syntax-highlighter#345]
After upgrading to WordPress 4.5 Crayon crashes when navigating to the default bbPress overiew page /forums/. The following PHP-error is shown in the logs:

`Fatal error: Invalid argument "header": [Content-Type] in .../wp-content/plugins/crayon-syntax-highlighter/crayon_wp.class.php on line 216`

WordPress 4.5, Crayon 2.8.2, bbPress 2.5.8
nginx 1.6.2, HHVM 3.12.1

**Comment by aramk** [comment]
I suspect it's because I called it incorrectly. Can you modify line 216 to read:
```
header('Content-Type: text/html');
```
The fix is in [a67b549]

**Comment by sesom42** [comment]
Thx for quick response. The fix works.

**Comment by aramk** [comment]
Great, thanks for the bug report. I'll push a new version.
