### ISSUE TITLE
bbPress formatting issue

### ISSUE THREAD

**Issue by romik84** [aramk/crayon-syntax-highlighter#347]
Hi,

new version 2.8.3 strip formatting of the bbPress threads and it displays in a plain text. Thanks.

**Comment by tech55541** [comment]
Hello,
Same problem here, possible issue in code can be located below.
https://wordpress.org/support/topic/crayon-plugin-strips-tags-on-my-forum-content#post-8288720

Thanks.

**Comment by aramk** [comment]
The removal of the tags was in response to the plugin being pulled due to a potential XSS (Cross-Site Scripting) issue. If a script tag or attribute is included in the tags, it can execute this when the page renders. I'll need to work towards a solution to allow all safe tags.

**Comment by tech55541** [comment]
Hello,
Possible fix can be found over here.
https://wordpress.org/support/topic/crayon-plugin-strips-tags-on-my-forum-content?replies=9#post-8350183

Thanks.

**Comment by aramk** [comment]
Ideally I'd like to blacklist any event attributes like `onload` and not whitelist all possible tags, since this would tamper less with user input.

**Comment by tech55541** [comment]
Hello,
True, however, I would not know how to do this in PHP, this seems like a quick fix until we can figure something else out.

Thanks.

**Comment by aramk** [comment]
Can you download the zip for 9e47ee4 and give it a go? It should only scrape script tags and event attributes which is sufficient to prevent XSS attacks I think.

**Comment by tech55541** [comment]
Hello,
I will try to test it on my test site by the end of the week.

Thanks.

**Comment by tech55541** [comment]
Hello,
Where and how do I download this .zip folder?

Thanks.

**Comment by aramk** [comment]
You can find it on the main github page for the project. The direct link is here: https://github.com/aramk/crayon-syntax-highlighter/archive/master.zip

**Comment by aramk** [comment]
I've had another user verify by email that the fix worked. I'll wait for a few others to confirm here before releasing.

**Comment by tech55541** [comment]
Hello,
Sorry for being lazy and not getting this tested as fast. It seems to be working, I would go ahead and push the update. Then you can let the users point out anymore bugs. With that line of code commented, that leaves your site open to all kinds of bad code.

Thanks.

**Comment by aramk** [comment]
Would be able to test the latest download again? I've made a further change to return plain text from the AJAX call, but it shouldn't affect the bbPress highlighting which is still working for me.

**Comment by tech55541** [comment]
Hello,
I just used your link above to download it again. I am guessing this is what you wanted us to test. I will test this in the next couple of hours and post back.

Thanks.

**Comment by tech55541** [comment]
Hello,
I just tested it from the link above, now this error is showing.

Warning: Missing argument 2 for CrayonUtil::strip_event_attributes(), called in /public_html/wp-content/plugins/crayon-syntax-highlighter/crayon_wp.class.php on line 204 and defined in /public_html/wp-content/plugins/crayon-syntax-highlighter/util/crayon_util.class.php on line 851

Thanks.

**Comment by aramk** [comment]
Thanks for testing. I've fixed that issue. That was a warning so it should otherwise be working?

**Comment by tech55541** [comment]
Hello,
Yes, it is working. Should I download and install the latest version again so that warning goes away?

Thanks.

**Comment by aramk** [comment]
Great! Up to you, but I should be able to publish this soon. Waiting on
feedback from one more person.

**Comment by tech55541** [comment]
Hello,
Alright, sounds good. I will go ahead and install the latest version to make the warning go away and check just to make sure everything is working good.

Thanks.

**Comment by tech55541** [comment]
Hello,
Just checked again, now the warning is gone.

Thanks.

**Comment by tech55541** [comment]
Hello,
Um, the update you released tonight has a major problem that needs to be fixed immediately. The update strips the paragraph tag from the BBPress topic and reply content.

Could you please look in to this? The beta version worked fine, you release the update and it screws up my forum. Not cool.

Thanks.

**Comment by aramk** [comment]
Hi, 2.8.3 is still the latest version released through Wordpress plugins. I haven't released anything yet. I suspect you updated back to this version from the 2.8.4 beta. Since the beta is not released, it will ask you to update to the latest (2.8.3) which reverted the fixes in 2.8.4 beta.

**Comment by tech55541** [comment]
Hello,
That makes since. Please update this when you push the new version out.

Thanks.

**Comment by harrymilatz** [comment]
Hello,

will be there an update (maybe just update the readme.txt) to WordPress 4.5.x?

I found no issue at the moment, so it could be enough to change the "tested up to" in the readme.txt

In the last updates the "tested up to" tag wasn't changed.

Best regards,
Harry

**Comment by aramk** [comment]
Updated this in e881910. Version 2.8.4 has been released.

**Comment by luxint66** [comment]
Thanks for the update. It's not stripping html from my forum now but it is stripping jwplayer <script> tags. Is there a way to whitelist certain tags without hacking the code?

Thanks

Lux
