### ISSUE TITLE
bash code with greater than and less than symbol's get converted to &gt; and &lt;

### ISSUE THREAD

**Issue by phrend** [aramk/crayon-syntax-highlighter#352]
When I have bash scripts that include `<` and/or `>` crayon converts them to `&gt;` and/or `&lt;`

Is there a way I can prevent this?

Thanks!

**Comment by kiview** [comment]
I have the same problem with Java and Groovy code. 
I use Jetpack and Markdown in conjunction with Crayon, maybe some compatibility problem?

**Comment by vitorhadad** [comment]
The same thing happens with Haskell code.

**Comment by Meligy** [comment]
The `decode` option is the right answer for this. I have it on by default actually.

**Comment by phrend** [comment]
@vitorhadad and @Meligy - Enabling `Decode HTML entities in code` did the trick! Thanks!
