### ISSUE TITLE
compatible to WordPress 4.5.x?

### ISSUE THREAD

**Issue by harrymilatz** [aramk/crayon-syntax-highlighter#356]
Hello,

as i wrote already here https://github.com/aramk/crayon-syntax-highlighter/issues/347 (i think it is wrong at this place), so here again;)

Will be there an update (maybe just update the readme.txt) to WordPress 4.5.x?

I found no issue at the moment which is based on the WP-Version 4.5.x, so it could be enough to change the "tested up to" in the readme.txt

In the last updates the "tested up to" tag wasn't changed.

Best regards,
Harry

**Comment by aramk** [comment]
Hi, updated in e881910.

**Comment by harrymilatz** [comment]
Hi,

thanks a lot:)
