### ISSUE TITLE
Adding a new language not working

### ISSUE THREAD

**Issue by morbidgames** [aramk/crayon-syntax-highlighter#364]
Solved it, it seems that we can't use flags in regular expressions for file languages (I was using `g`).

**Comment by aramk** [comment]
👍

**Comment by morbidgames** [comment]
Is there a reason why `non-capturing` groups don't work in the regular expressions of language files? (they're all captured/css class is applied to non-capturing groups)

**Comment by aramk** [comment]
If you mean `(?:)` they should be still matching. It's using the PHP regex engine, if that has any intricacies.

**Comment by morbidgames** [comment]
Got it, thanks :+1:
