### ISSUE TITLE
Error after dropping a comment on WordPress 4.5.3

### ISSUE THREAD

**Issue by tjoudeh** [aramk/crayon-syntax-highlighter#366]
Hello Aram,
My blog http://bitoftech.net is running WordPress version 4.5.3, a lot of readers told me that they are receiving the below error after they try to post a comment. I was able to reproduce this error by dropping a comment. Taking into consideration that I receive the comment successfully. Could you please check? I'm running the latest version of your plugin.

Appreciate your feedback.

Error Details:

Notice: Trying to get property of non-object in /home3/bitoftec/public_html/wp-content/plugins/crayon-syntax-highlighter/crayon_wp.class.php on line 717

Warning: Cannot modify header information - headers already sent by (output started at /home3/bitoftec/public_html/wp-content/plugins/crayon-syntax-highlighter/crayon_wp.class.php:717) in /home3/bitoftec/public_html/wp-includes/comment.php on line 517

**Comment by aramk** [comment]
Should be fixed in the latest
