### ISSUE TITLE
Php 7.0 Support

### ISSUE THREAD

**Issue by dschense** [aramk/crayon-syntax-highlighter#384]
/wp-content/plugins/crayon-syntax-highlighter/crayon_settings.class.php
---------------------------------------------------------------------------------------------------------------------------------
FOUND 1 ERROR AFFECTING 1 LINE
---------------------------------------------------------------------------------------------------------------------------------
 87 | ERROR | Function name, class name, namespace name or constant name can not be reserved keyword 'MIXED' (since version 7.0)
---------------------------------------------------------------------------------------------------------------------------------

The plugin is not working on a Php 7.0 Setup.
hope a fix is coming soon ;)

**Comment by edwarddekker** [comment]
This issue is already fixed. See this post #378 and #381.
