### ISSUE TITLE
How to deploy crayon-syntax-highlighter on other PHP environment?

### ISSUE THREAD

**Issue by windcloud-409** [aramk/crayon-syntax-highlighter#406]
In README I noticed:
> can be used in any PHP environment

How to deploy crayon-syntax-highlighter on other PHP environment? I am not a WordPress user and wanna use crayon-syntax-highlighter in my own PHP project.

Whether a guide can be provided? Thanks.

**Comment by tahmasebi** [comment]
use `CrayonWP::highlight` in `/crayon_wp.class.php`

**Comment by aramk** [comment]
Have a look at:

http://aramk.com/blog/2012/05/30/adding-crayon-to-posts-in-wordpress-programmatically/
http://aramk.com/blog/2012/05/03/using-crayon-manually-in-php/
