### ISSUE TITLE
Non well formed numeric value encountered

### ISSUE THREAD

**Issue by Beee4life** [aramk/crayon-syntax-highlighter#442]
I came across this error: 
```
A non well formed numeric value encountered in /Users/Beee/HTML/beee/webapp/content/plugins/crayon-syntax-highlighter/crayon_formatter.class.php on line 118
A non well formed numeric value encountered in /Users/Beee/HTML/beee/webapp/content/plugins/crayon-syntax-highlighter/crayon_formatter.class.php on line 119
```

**Comment by moritzkiehl** [comment]
Hi I found the origin and Solution to this error.

$toolbar_height = $_font_size * 1.5 . 'px !important;';
$info_height = $_font_size * 1.4 . 'px !important;';

In my Version $_font_size was $font_size which is a String and can't be multiplied with 1.5

**Comment by Beee4life** [comment]
Nice find but since the plugin author doesn't seem to be keen on support I have moved on to a similar plugin. It has less 'UI' settings, but you can tweak it a lot if needed.

See https://wordpress.org/plugins/wp-geshi-highlight/

Maybe if the author delivers proper support, I would go back, but not before it's fixed...

**Comment by Beee4life** [comment]
Closing this topic to clean up my 'active' list of issues and not using the plugin anymore anyway.
