### ISSUE TITLE
Error: < Can not convert to &lt;

### ISSUE THREAD

**Issue by hochan222** [aramk/crayon-syntax-highlighter#472]
```
 &lt;Table className={classes.table} aria-label="Member Form">
          &lt;TableBody>
            &lt;TableRow>
              &lt;TableCell align="center">
```
Hi I am a WordPress user who is using crayon-syntax-highlighter well.
Is experiencing a problem that '<' cannot be converted properly. Please check out the link below!

http://ghcksdk.com/toasteditor-textarea-editor/

Thank you!

**Comment by worldsdream** [comment]
Crayon is great! Only it’s not being updated anymore. The good thing is that there is a fork of this awesome plugin.

If you do have problems, let the developer know on the support page of the plugin. 

https://wordpress.org/plugins/urvanov-syntax-highlighter/

**Comment by hochan222** [comment]
Thank you for reply!! 
It must have been modified for a long time!
