### ISSUE TITLE
Plugin Abandoned - reported by a wordpress tool.

### ISSUE THREAD

**Issue by catafest** [aramk/crayon-syntax-highlighter#482]
_The Plugin "Crayon Syntax Highlighter" appears to be abandoned (updated 10/05/2016, tested to WP 4.2.0).
Type: Plugin Abandoned_
this is true? crayon-syntax-highlighter is abandoned?

**Comment by veggiespam** [comment]
It's abandoned.  Try https://wordpress.org/plugins/urvanov-syntax-highlighter/ instead, the developer has taken over the Crayon codebase.  You will lose your existing Crayon setting and have to re-configure it, but it otherwise works great in PHP 8.0+ and WP 5.7+.

**Comment by catafest** [comment]
Thank you for your reply.
