### ISSUE TITLE
crayon on custom post type

### ISSUE THREAD

**Issue by coopersita** [aramk/crayon-syntax-highlighter#67]
Does it only work on Posts? It doesn't seem to work on my custom post types.  

Thanks

**Comment by tb-admin** [comment]
When using CrayonWP::highlight() I get:

Warning: Cannot modify header information - headers already sent by (output started at .../header.php:2) in .../wp-content/plugins/crayon-syntax-highlighter/crayon_wp.class.php on line 219

Headers should not be set after Wordpress/Theme have already set them. Can you update your code to only print headers when needed. I am assuming this is for AJAX calls.

**Comment by styledev** [comment]
When using CrayonWP::highlight() I get:

Warning: Cannot modify header information - headers already sent by (output started at .../header.php:2) in .../wp-content/plugins/crayon-syntax-highlighter/crayon_wp.class.php on line 219

Headers should not be set after Wordpress/Theme have already set them. Can you update your code to only print headers when needed. I am assuming this is for AJAX calls.

**Comment by mikehike123** [comment]
Old post, I realize.  I ran into the same problem as styledev  and ended up doing the following so I could modify the highlight() method to not send headers:

```
// this is just so we can use syntext highlighting and the crayon plugin needs to be modified a little.
if(class_exists('CrayonWP')):
    class MyHighlight extends CrayonWP
    {
        public static function highlight($code, $add_tags = FALSE, $output_text = FALSE) {
        $captures = CrayonWP::capture_crayons(0, $code);
        $the_captures = $captures['capture'];
        if (count($the_captures) == 0 && $add_tags) {
            // Nothing captured, so wrap in a pre and try again
            $code = '<pre>' . $code . '</pre>';
            $captures = CrayonWP::capture_crayons(0, $code);
            $the_captures = $captures['capture'];
        }
        $the_content = $captures['content'];
        $the_content = CrayonUtil::strip_tags_blacklist($the_content, array('script'));
        $the_content = CrayonUtil::strip_event_attributes($the_content);
        foreach ($the_captures as $id => $capture) {
            $atts = $capture['atts'];
            $no_enqueue = array(
                CrayonSettings::ENQUEUE_THEMES => FALSE,
                CrayonSettings::ENQUEUE_FONTS => FALSE);
            $atts = array_merge($atts, $no_enqueue);
            $code = $capture['code'];
            $crayon = CrayonWP::shortcode($atts, $code, $id);
            $crayon_formatted = $crayon->output(TRUE, FALSE);
            $the_content = CrayonUtil::preg_replace_escape_back(self::regex_with_id($id), $crayon_formatted, $the_content, 1, $count);
        }

       
        return $the_content;
    }
    }
  endif;

```
